//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2022 March 06 22:26:05 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections;
using System.Runtime.CompilerServices;

#nullable enable

namespace go
{
    public static partial class main_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct MyComplex64
        {
            // Value of the MyComplex64 struct
            private readonly complex64 m_value;
            
            public MyComplex64(complex64 value) => m_value = value;

            // Enable implicit conversions between complex64 and MyComplex64 struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator MyComplex64(complex64 value) => new MyComplex64(value);
            
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator complex64(MyComplex64 value) => value.m_value;
            
            // Enable comparisons between nil and MyComplex64 struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(MyComplex64 value, NilType nil) => value.Equals(default(MyComplex64));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(MyComplex64 value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, MyComplex64 value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, MyComplex64 value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator MyComplex64(NilType nil) => default(MyComplex64);
        }
    }
}
