//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 09 05:44:57 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using fmt = go.fmt_package;
using ast = go.go.ast_package;
using parser = go.go.parser_package;
using token = go.go.token_package;
using os = go.os_package;
using path = go.path_package;
using reflect = go.reflect_package;
using strconv = go.strconv_package;
using strings = go.strings_package;

#nullable enable

namespace go
{
    public static partial class main_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct fix
        {
            // Constructors
            public fix(NilType _)
            {
                this.name = default;
                this.date = default;
                this.f = default;
                this.desc = default;
                this.disabled = default;
            }

            public fix(@string name = default, @string date = default, Func<ptr<ast.File>, bool> f = default, @string desc = default, bool disabled = default)
            {
                this.name = name;
                this.date = date;
                this.f = f;
                this.desc = desc;
                this.disabled = disabled;
            }

            // Enable comparisons between nil and fix struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(fix value, NilType nil) => value.Equals(default(fix));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(fix value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, fix value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, fix value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator fix(NilType nil) => default(fix);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        private static fix fix_cast(dynamic value)
        {
            return new fix(value.name, value.date, value.f, value.desc, value.disabled);
        }
    }
}