//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 10:09:24 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using fmt = go.fmt_package;
using ast = go.go.ast_package;
using printer = go.go.printer_package;
using strings = go.strings_package;

namespace go
{
    public static partial class main_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct MethodSig
        {
            // Constructors
            public MethodSig(NilType _)
            {
                this.args = default;
                this.results = default;
            }

            public MethodSig(slice<@string> args = default, slice<@string> results = default)
            {
                this.args = args;
                this.results = results;
            }

            // Enable comparisons between nil and MethodSig struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(MethodSig value, NilType nil) => value.Equals(default(MethodSig));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(MethodSig value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, MethodSig value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, MethodSig value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator MethodSig(NilType nil) => default(MethodSig);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static MethodSig MethodSig_cast(dynamic value)
        {
            return new MethodSig(value.args, value.results);
        }
    }
}