//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 08 03:41:55 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using fmt = go.fmt_package;
using strings = go.strings_package;
using unicode = go.unicode_package;
using utf8 = go.unicode.utf8_package;
using go;

namespace go {
namespace text {
namespace template
{
    public static partial class parse_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct lexer
        {
            // Constructors
            public lexer(NilType _)
            {
                this.name = default;
                this.input = default;
                this.leftDelim = default;
                this.rightDelim = default;
                this.trimRightDelim = default;
                this.pos = default;
                this.start = default;
                this.width = default;
                this.items = default;
                this.parenDepth = default;
                this.line = default;
                this.startLine = default;
            }

            public lexer(@string name = default, @string input = default, @string leftDelim = default, @string rightDelim = default, @string trimRightDelim = default, Pos pos = default, Pos start = default, Pos width = default, channel<item> items = default, long parenDepth = default, long line = default, long startLine = default)
            {
                this.name = name;
                this.input = input;
                this.leftDelim = leftDelim;
                this.rightDelim = rightDelim;
                this.trimRightDelim = trimRightDelim;
                this.pos = pos;
                this.start = start;
                this.width = width;
                this.items = items;
                this.parenDepth = parenDepth;
                this.line = line;
                this.startLine = startLine;
            }

            // Enable comparisons between nil and lexer struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(lexer value, NilType nil) => value.Equals(default(lexer));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(lexer value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, lexer value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, lexer value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator lexer(NilType nil) => default(lexer);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        private static lexer lexer_cast(dynamic value)
        {
            return new lexer(value.name, value.input, value.leftDelim, value.rightDelim, value.trimRightDelim, value.pos, value.start, value.width, value.items, value.parenDepth, value.line, value.startLine);
        }
    }
}}}