//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 09:29:11 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using bytes = go.bytes_package;
using binary = go.encoding.binary_package;
using fmt = go.fmt_package;
using html = go.html_package;
using os = go.os_package;
using sort = go.sort_package;
using ssa = go.cmd.compile.@internal.ssa_package;
using types = go.cmd.compile.@internal.types_package;
using obj = go.cmd.@internal.obj_package;
using objabi = go.cmd.@internal.objabi_package;
using src = go.cmd.@internal.src_package;
using sys = go.cmd.@internal.sys_package;
using go;

namespace go {
namespace cmd {
namespace compile {
namespace @internal
{
    public static partial class gc_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct sfRtCallDef
        {
            // Constructors
            public sfRtCallDef(NilType _)
            {
                this.rtfn = default;
                this.rtype = default;
            }

            public sfRtCallDef(ref ptr<obj.LSym> rtfn = default, types.EType rtype = default)
            {
                this.rtfn = rtfn;
                this.rtype = rtype;
            }

            // Enable comparisons between nil and sfRtCallDef struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(sfRtCallDef value, NilType nil) => value.Equals(default(sfRtCallDef));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(sfRtCallDef value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, sfRtCallDef value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, sfRtCallDef value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator sfRtCallDef(NilType nil) => default(sfRtCallDef);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        private static sfRtCallDef sfRtCallDef_cast(dynamic value)
        {
            return new sfRtCallDef(ref value.rtfn, value.rtype);
        }
    }
}}}}