//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 09 05:43:22 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using types = go.cmd.compile.@internal.types_package;
using src = go.cmd.@internal.src_package;
using sort = go.sort_package;
using go;

#nullable enable

namespace go {
namespace cmd {
namespace compile {
namespace @internal
{
    public static partial class gc_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct typeSetEntry
        {
            // Constructors
            public typeSetEntry(NilType _)
            {
                this.pos = default;
                this.typ = default;
            }

            public typeSetEntry(src.XPos pos = default, ref ptr<types.Type> typ = default)
            {
                this.pos = pos;
                this.typ = typ;
            }

            // Enable comparisons between nil and typeSetEntry struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(typeSetEntry value, NilType nil) => value.Equals(default(typeSetEntry));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(typeSetEntry value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, typeSetEntry value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, typeSetEntry value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator typeSetEntry(NilType nil) => default(typeSetEntry);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        private static typeSetEntry typeSetEntry_cast(dynamic value)
        {
            return new typeSetEntry(value.pos, ref value.typ);
        }
    }
}}}}