//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 09:29:25 UTC
// </auto-generated>
//---------------------------------------------------------
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using go;

namespace go {
namespace cmd {
namespace compile {
namespace @internal
{
    public static partial class gc_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct constIntNodesByVal
        {
            // Value of the constIntNodesByVal struct
            private readonly slice<ref Node> m_value;

            public constIntNodesByVal(slice<ref Node> value) => m_value = value;

            // Enable implicit conversions between slice<ref Node> and constIntNodesByVal struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator constIntNodesByVal(slice<ref Node> value) => new constIntNodesByVal(value);
            
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator slice<ref Node>(constIntNodesByVal value) => value.m_value;
            
            // Enable comparisons between nil and constIntNodesByVal struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(constIntNodesByVal value, NilType nil) => value.Equals(default(constIntNodesByVal));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(constIntNodesByVal value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, constIntNodesByVal value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, constIntNodesByVal value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator constIntNodesByVal(NilType nil) => default(constIntNodesByVal);
        }
    }
}}}}
