//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 09 05:43:24 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using ssa = go.cmd.compile.@internal.ssa_package;
using types = go.cmd.compile.@internal.types_package;
using obj = go.cmd.@internal.obj_package;
using objabi = go.cmd.@internal.objabi_package;
using src = go.cmd.@internal.src_package;
using sort = go.sort_package;
using go;

#nullable enable

namespace go {
namespace cmd {
namespace compile {
namespace @internal
{
    public static partial class gc_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct Param
        {
            // Constructors
            public Param(NilType _)
            {
                this.Ntype = default;
                this.Heapaddr = default;
                this.Stackcopy = default;
                this.Innermost = default;
                this.Outer = default;
                this.Pragma = default;
                this.Alias = default;
            }

            public Param(ref ptr<Node> Ntype = default, ref ptr<Node> Heapaddr = default, ref ptr<Node> Stackcopy = default, ref ptr<Node> Innermost = default, ref ptr<Node> Outer = default, PragmaFlag Pragma = default, bool Alias = default)
            {
                this.Ntype = Ntype;
                this.Heapaddr = Heapaddr;
                this.Stackcopy = Stackcopy;
                this.Innermost = Innermost;
                this.Outer = Outer;
                this.Pragma = Pragma;
                this.Alias = Alias;
            }

            // Enable comparisons between nil and Param struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(Param value, NilType nil) => value.Equals(default(Param));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(Param value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, Param value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, Param value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator Param(NilType nil) => default(Param);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static Param Param_cast(dynamic value)
        {
            return new Param(ref value.Ntype, ref value.Heapaddr, ref value.Stackcopy, ref value.Innermost, ref value.Outer, value.Pragma, value.Alias);
        }
    }
}}}}