//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 09:58:40 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using fmt = go.fmt_package;

namespace go
{
    public static partial class main_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct T17
        {
            // Constructors
            public T17(NilType _)
            {
                this.pre = default;
                this.mid = default;
                this.post = default;
            }

            public T17(array<byte> pre = default, array<byte> mid = default, array<byte> post = default)
            {
                this.pre = pre;
                this.mid = mid;
                this.post = post;
            }

            // Enable comparisons between nil and T17 struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(T17 value, NilType nil) => value.Equals(default(T17));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(T17 value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, T17 value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, T17 value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator T17(NilType nil) => default(T17);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static T17 T17_cast(dynamic value)
        {
            return new T17(value.pre, value.mid, value.post);
        }
    }
}