//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2022 March 13 05:52:09 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;

using go;

#nullable enable

namespace go {
namespace @internal
{
    public static partial class xcoff_package
    {
        [GeneratedCode("go2cs", "0.1.2.0")]
        public partial struct AuxFcn64
        {
            // Constructors
            public AuxFcn64(NilType _)
            {
                this.Xlnnoptr = default;
                this.Xfsize = default;
                this.Xendndx = default;
                this.Xpad = default;
                this.Xauxtype = default;
            }

            public AuxFcn64(ulong Xlnnoptr = default, uint Xfsize = default, uint Xendndx = default, byte Xpad = default, byte Xauxtype = default)
            {
                this.Xlnnoptr = Xlnnoptr;
                this.Xfsize = Xfsize;
                this.Xendndx = Xendndx;
                this.Xpad = Xpad;
                this.Xauxtype = Xauxtype;
            }

            // Enable comparisons between nil and AuxFcn64 struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(AuxFcn64 value, NilType nil) => value.Equals(default(AuxFcn64));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(AuxFcn64 value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, AuxFcn64 value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, AuxFcn64 value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator AuxFcn64(NilType nil) => default(AuxFcn64);
        }

        [GeneratedCode("go2cs", "0.1.2.0")]
        public static AuxFcn64 AuxFcn64_cast(dynamic value)
        {
            return new AuxFcn64(value.Xlnnoptr, value.Xfsize, value.Xendndx, value.Xpad, value.Xauxtype);
        }
    }
}}