//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 09 04:53:15 UTC
// </auto-generated>
//---------------------------------------------------------
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using go;

#nullable enable

namespace go {
namespace math
{
    public static partial class big_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct Word
        {
            // Value of the Word struct
            private readonly ulong m_value;

            public Word(ulong value) => m_value = value;

            // Enable implicit conversions between ulong and Word struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator Word(ulong value) => new Word(value);
            
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator ulong(Word value) => value.m_value;
            
            // Enable comparisons between nil and Word struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(Word value, NilType nil) => value.Equals(default(Word));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(Word value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, Word value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, Word value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator Word(NilType nil) => default(Word);
        }
    }
}}
