//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2022 March 13 05:52:40 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;

using go;

#nullable enable

namespace go {
namespace go
{
    public static partial class e_package
    {
        [GeneratedCode("go2cs", "0.1.2.0")]
        public partial struct U1
        {
            // Constructors
            public U1(NilType _)
            {
                this.ptr<U1> = default;
            }

            public U1(ref ptr<U1> ptr<U1> = default)
            {
                this.ptr<U1> = ptr<U1>;
            }

            // Enable comparisons between nil and U1 struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(U1 value, NilType nil) => value.Equals(default(U1));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(U1 value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, U1 value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, U1 value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator U1(NilType nil) => default(U1);
        }

        [GeneratedCode("go2cs", "0.1.2.0")]
        public static U1 U1_cast(dynamic value)
        {
            return new U1(ref value.ptr<U1>);
        }
    }
}}