//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 09 05:51:31 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using bytes = go.bytes_package;
using bio = go.cmd.@internal.bio_package;
using dwarf = go.cmd.@internal.dwarf_package;
using objabi = go.cmd.@internal.objabi_package;
using sys = go.cmd.@internal.sys_package;
using sym = go.cmd.oldlink.@internal.sym_package;
using fmt = go.fmt_package;
using log = go.log_package;
using sort = go.sort_package;
using strconv = go.strconv_package;
using strings = go.strings_package;
using go;

#nullable enable

namespace go {
namespace cmd {
namespace oldlink {
namespace @internal
{
    public static partial class loader_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct objIdx
        {
            // Constructors
            public objIdx(NilType _)
            {
                this.r = default;
                this.i = default;
                this.e = default;
            }

            public objIdx(ref ptr<oReader> r = default, Sym i = default, Sym e = default)
            {
                this.r = r;
                this.i = i;
                this.e = e;
            }

            // Enable comparisons between nil and objIdx struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(objIdx value, NilType nil) => value.Equals(default(objIdx));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(objIdx value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, objIdx value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, objIdx value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator objIdx(NilType nil) => default(objIdx);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        private static objIdx objIdx_cast(dynamic value)
        {
            return new objIdx(ref value.r, value.i, value.e);
        }
    }
}}}}