//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 08:51:45 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using fmt = go.fmt_package;
using log = go.log_package;
using os = go.os_package;
using strings = go.strings_package;
using scanner = go.text.scanner_package;
using src = go.cmd.@internal.src_package;
using go;

namespace go {
namespace cmd {
namespace asm {
namespace @internal
{
    public static partial class lex_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct Token
        {
            // Constructors
            public Token(NilType _)
            {
                this.ScanToken = default;
                this.text = default;
            }

            public Token(ScanToken ScanToken = default, @string text = default)
            {
                this.ScanToken = ScanToken;
                this.text = text;
            }

            // Enable comparisons between nil and Token struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(Token value, NilType nil) => value.Equals(default(Token));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(Token value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, Token value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, Token value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator Token(NilType nil) => default(Token);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static Token Token_cast(dynamic value)
        {
            return new Token(value.ScanToken, value.text);
        }
    }
}}}}