//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2022 March 06 23:20:55 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using bytes = go.bytes_package;
using gcprog = go.cmd.@internal.gcprog_package;
using objabi = go.cmd.@internal.objabi_package;
using sys = go.cmd.@internal.sys_package;
using loader = go.cmd.link.@internal.loader_package;
using sym = go.cmd.link.@internal.sym_package;
using zlib = go.compress.zlib_package;
using elf = go.debug.elf_package;
using binary = go.encoding.binary_package;
using fmt = go.fmt_package;
using log = go.log_package;
using os = go.os_package;
using sort = go.sort_package;
using strconv = go.strconv_package;
using strings = go.strings_package;
using sync = go.sync_package;
using atomic = go.sync.atomic_package;
using go;

#nullable enable

namespace go {
namespace cmd {
namespace link {
namespace @internal
{
    public static partial class ld_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct dodataState
        {
            // Constructors
            public dodataState(NilType _)
            {
                this.ctxt = default;
                this.data = default;
                this.dataMaxAlign = default;
                this.symGroupType = default;
                this.datsize = default;
            }

            public dodataState(ref ptr<Link> ctxt = default, array<slice<loader.Sym>> data = default, array<int> dataMaxAlign = default, slice<sym.SymKind> symGroupType = default, long datsize = default)
            {
                this.ctxt = ctxt;
                this.data = data;
                this.dataMaxAlign = dataMaxAlign;
                this.symGroupType = symGroupType;
                this.datsize = datsize;
            }

            // Enable comparisons between nil and dodataState struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(dodataState value, NilType nil) => value.Equals(default(dodataState));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(dodataState value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, dodataState value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, dodataState value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator dodataState(NilType nil) => default(dodataState);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        private static dodataState dodataState_cast(dynamic value)
        {
            return new dodataState(ref value.ctxt, value.data, value.dataMaxAlign, value.symGroupType, value.datsize);
        }
    }
}}}}