//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2022 March 06 23:22:19 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using objabi = go.cmd.@internal.objabi_package;
using sys = go.cmd.@internal.sys_package;
using loader = go.cmd.link.@internal.loader_package;
using sym = go.cmd.link.@internal.sym_package;
using pe = go.debug.pe_package;
using binary = go.encoding.binary_package;
using fmt = go.fmt_package;
using buildcfg = go.@internal.buildcfg_package;
using sort = go.sort_package;
using strconv = go.strconv_package;
using strings = go.strings_package;
using go;

#nullable enable

namespace go {
namespace cmd {
namespace link {
namespace @internal
{
    public static partial class ld_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct Imp
        {
            // Constructors
            public Imp(NilType _)
            {
                this.s = default;
                this.off = default;
                this.next = default;
                this.argsize = default;
            }

            public Imp(loader.Sym s = default, ulong off = default, ref ptr<Imp> next = default, nint argsize = default)
            {
                this.s = s;
                this.off = off;
                this.next = next;
                this.argsize = argsize;
            }

            // Enable comparisons between nil and Imp struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(Imp value, NilType nil) => value.Equals(default(Imp));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(Imp value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, Imp value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, Imp value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator Imp(NilType nil) => default(Imp);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static Imp Imp_cast(dynamic value)
        {
            return new Imp(value.s, value.off, ref value.next, value.argsize);
        }
    }
}}}}