//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 08 03:22:56 UTC
// </auto-generated>
//---------------------------------------------------------
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;

namespace go
{
    public static partial class runtime_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct selectDir
        {
            // Value of the selectDir struct
            private readonly long m_value;

            public selectDir(long value) => m_value = value;

            // Enable implicit conversions between long and selectDir struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator selectDir(long value) => new selectDir(value);
            
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator long(selectDir value) => value.m_value;
            
            // Enable comparisons between nil and selectDir struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(selectDir value, NilType nil) => value.Equals(default(selectDir));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(selectDir value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, selectDir value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, selectDir value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator selectDir(NilType nil) => default(selectDir);
        }
    }
}
