// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/abi", new string[]
        {
            "abi.go",
            "abi_amd64.go",
            "abi_arm64.go",
            "abi_generic.go",
            "abi_loong64.go",
            "abi_ppc64x.go",
            "abi_riscv64.go",
            "abi_test.go",
            "compiletype.go",
            "escape.go",
            "export_test.go",
            "funcpc.go",
            "funcpc_gccgo.go",
            "iface.go",
            "map.go",
            "rangefuncconsts.go",
            "runtime.go",
            "stack.go",
            "switch.go",
            "symtab.go",
            "testdata/x.go",
            "testdata/x.s",
            "type.go",
        });
        registry.Add("TestFuncPC", abi_test_package.TestFuncPC, "abi_test.go", 15);
        registry.Add("TestFuncPCCompileError", abi_test_package.TestFuncPCCompileError, "abi_test.go", 32);
        return TestHost.Run(registry, args);
    }
}
