// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace go2cs.Templates
{
    using System.Collections.Generic;
    using System.Linq;
    using go2cs;
    using go2cs.Metadata;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class StructTypeTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 1 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
 // This template creates a <PackageName>_<StructName>Struct.cs file 
            
            #line default
            #line hidden
            this.Write(@"//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on ");
            
            #line 17 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedTime));
            
            #line default
            #line hidden
            this.Write("\r\n// </auto-generated>\r\n//-------------------------------------------------------" +
                    "--\r\nusing System;\r\nusing System.CodeDom.Compiler;\r\nusing System.Diagnostics;\r\nus" +
                    "ing System.Reflection;\r\nusing System.Runtime.CompilerServices;\r\n");
            
            #line 25 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(Environment.NewLine, UsingStatements)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 26 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
if (!NamespacePrefix.Equals("go")) {
            
            #line default
            #line hidden
            this.Write("using go;\r\n");
            
            #line 28 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#nullable enable\r\n\r\n");
            
            #line 32 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NamespaceHeader));
            
            #line default
            #line hidden
            this.Write("\r\n    public static partial class ");
            
            #line 33 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PackageName));
            
            #line default
            #line hidden
            this.Write("_package\r\n    {\r\n        [");
            
            #line 35 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedCodeAttribute));
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 35 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

        foreach (string promotedStruct in PromotedStructs)
        {
            if (!string.IsNullOrEmpty(promotedStruct))
            {
        
            
            #line default
            #line hidden
            this.Write("\r\n        [PromotedStruct(typeof(");
            
            #line 42 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(promotedStruct));
            
            #line default
            #line hidden
            this.Write("))]");
            
            #line 42 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

            }
        }
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 46 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Scope));
            
            #line default
            #line hidden
            this.Write(" partial struct ");
            
            #line 46 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write("\r\n        {");
            
            #line 47 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

            foreach (KeyValuePair<string, List<FunctionSignature>> kvp in PromotedFunctions)
            {
                foreach (var decl in kvp.Value)
                {
                    
            
            #line default
            #line hidden
            
            #line 52 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new StructFuncDeclTemplate
                    {
                        PromotedField = kvp.Key,
                        FunctionName = decl.Name,
                        Scope = "public",
                        ParameterSignature = decl.Signature.GenerateParametersSignature(),
                        ParameterNames = GetParameterNames(decl),
                        ParameterTypes = GetParameterTypeNames(decl),
                        ResultType = decl.Signature.GenerateResultSignature()
                    }
                    .TransformText()));
            
            #line default
            #line hidden
            
            #line 62 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

                }
            }

            foreach (KeyValuePair<string, List<FieldInfo>> kvp in PromotedFields)
            {

                FieldInfo promotedStruct = GetPromotedStruct(kvp.Key);
                bool isPointer = promotedStruct?.Type is PointerTypeInfo;
            
            
            #line default
            #line hidden
            this.Write("\r\n            // ");
            
            #line 73 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(" structure promotion - sourced from ");
            
            #line 73 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPointer ? "pointer" : "value copy"));
            
            #line default
            #line hidden
            this.Write("\r\n            private readonly ptr<");
            
            #line 74 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("> m_");
            
            #line 74 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("Ref;\r\n\r\n            private ref ");
            
            #line 76 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 76 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 76 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPointer ? "ptr" : "val"));
            
            #line default
            #line hidden
            this.Write(" => ref m_");
            
            #line 76 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("Ref.Value;\r\n");
            
            #line 77 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"


                foreach (var decl in kvp.Value)
                {
                
            
            #line default
            #line hidden
            this.Write("\r\n            public ref ");
            
            #line 83 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Type.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 83 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Name));
            
            #line default
            #line hidden
            this.Write(" => ref m_");
            
            #line 83 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("Ref.Value.");
            
            #line 83 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 84 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

                }
            }
            
            if (PromotedFunctions.Count > 0)
            {
            
            
            #line default
            #line hidden
            this.Write("            \r\n            [DebuggerStepperBoundary]\r\n            static ");
            
            #line 93 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write("()\r\n            {\r\n                Type targetType = typeof(");
            
            #line 95 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write(");\r\n                MethodInfo? extensionMethod;");
            
            #line 96 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"


                foreach (KeyValuePair<string, List<FunctionSignature>> kvp in PromotedFunctions)
                {
                    foreach (var decl in kvp.Value)
                    {
                        
            
            #line default
            #line hidden
            
            #line 102 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new StructFuncInitTemplate
                        {
                            FunctionName = decl.Name
                        }
                        .TransformText()));
            
            #line default
            #line hidden
            
            #line 106 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

                    }
                }
            
            #line default
            #line hidden
            this.Write("\r\n            }\r\n");
            
            #line 111 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

            
            }
            
            #line default
            #line hidden
            this.Write("\r\n            // Constructors\r\n            public ");
            
            #line 116 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write("(NilType _)\r\n            {");
            
            #line 117 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

            foreach (var decl in StructFields)
            {
                if (PromotedStructs.Contains(decl.Type.TypeName))
                {
                    // Promoted struct 
            
            #line default
            #line hidden
            this.Write("\r\n                this.m_");
            
            #line 124 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Name));
            
            #line default
            #line hidden
            this.Write("Ref = new ptr<");
            
            #line 124 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Type.TypeName));
            
            #line default
            #line hidden
            this.Write(">(new ");
            
            #line 124 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Type.TypeName));
            
            #line default
            #line hidden
            this.Write("(nil));");
            
            #line 124 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

                }
                else
                {
                    // Promoted interface or normal struct field 
            
            #line default
            #line hidden
            this.Write("\r\n                this.");
            
            #line 130 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Name));
            
            #line default
            #line hidden
            this.Write(" = default;");
            
            #line 130 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

                }
            }
            
            #line default
            #line hidden
            this.Write("\r\n            }");
            
            #line 134 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
 
            
            if (StructFields.Length > 0)
            {
            
            #line default
            #line hidden
            this.Write("\r\n\r\n            public ");
            
            #line 140 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 140 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", StructFields.Select(field => $"{(field.Type is PointerTypeInfo ? "ref " : "")}{field.Type.TypeName} {field.Name} = default"))));
            
            #line default
            #line hidden
            this.Write(")\r\n            {");
            
            #line 141 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

            foreach (var decl in StructFields)
            {
                if (PromotedStructs.Contains(decl.Type.TypeName))
                {
                    // Promoted struct 
            
            #line default
            #line hidden
            this.Write("\r\n                this.m_");
            
            #line 148 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Name));
            
            #line default
            #line hidden
            this.Write("Ref = new ptr<");
            
            #line 148 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Type.TypeName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 148 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Type is PointerTypeInfo ? "ref " : ""));
            
            #line default
            #line hidden
            
            #line 148 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Name));
            
            #line default
            #line hidden
            this.Write(");");
            
            #line 148 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

                }
                else
                {
                    // Promoted interface or normal struct field 
            
            #line default
            #line hidden
            this.Write("\r\n                this.");
            
            #line 154 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 154 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decl.Name));
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 154 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

                }
            }
            
            #line default
            #line hidden
            this.Write("\r\n            }\r\n");
            
            #line 159 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

            }
            
            #line default
            #line hidden
            this.Write("\r\n            // Enable comparisons between nil and ");
            
            #line 162 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write(" struct\r\n            [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n        " +
                    "    public static bool operator ==(");
            
            #line 164 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write(" value, NilType nil) => value.Equals(default(");
            
            #line 164 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write("));\r\n\r\n            [MethodImpl(MethodImplOptions.AggressiveInlining)]\r\n          " +
                    "  public static bool operator !=(");
            
            #line 167 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write(" value, NilType nil) => !(value == nil);\r\n\r\n            [MethodImpl(MethodImplOpt" +
                    "ions.AggressiveInlining)]\r\n            public static bool operator ==(NilType ni" +
                    "l, ");
            
            #line 170 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write(" value) => value == nil;\r\n\r\n            [MethodImpl(MethodImplOptions.AggressiveI" +
                    "nlining)]\r\n            public static bool operator !=(NilType nil, ");
            
            #line 173 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write(" value) => value != nil;\r\n\r\n            [MethodImpl(MethodImplOptions.AggressiveI" +
                    "nlining)]\r\n            public static implicit operator ");
            
            #line 176 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write("(NilType nil) => default(");
            
            #line 176 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        [");
            
            #line 179 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratedCodeAttribute));
            
            #line default
            #line hidden
            this.Write("]\r\n        ");
            
            #line 180 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Scope));
            
            #line default
            #line hidden
            this.Write(" static ");
            
            #line 180 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 180 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write("_cast(dynamic value)\r\n        {\r\n            return new ");
            
            #line 182 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 182 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetConstructorParameterNames()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n    }\r\n");
            
            #line 185 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NamespaceFooter));
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 185 "D:\Projects\go2cs\src\go2cs.Templates\StructTypeTemplate.tt"

// Template Parameters
public string NamespacePrefix;
public string NamespaceHeader;
public string NamespaceFooter;
public string PackageName;
public string StructName;
public string Scope;
public FieldInfo[] StructFields;
public HashSet<string> PromotedStructs;
public Dictionary<string, List<FunctionSignature>> PromotedFunctions;
public Dictionary<string, List<FieldInfo>> PromotedFields;
public IEnumerable<string> UsingStatements;

private string GetParameterNames(FunctionSignature function)
{
    string parameterNames = function.GetParameterNames();

    if (parameterNames.Length > 0)
        parameterNames = ", " + parameterNames;

    return parameterNames;
}

private string GetConstructorParameterNames()
{
    return string.Join(", ", StructFields.Select(field => $"{(field.Type is PointerTypeInfo ? "ref " : "")}value.{field.Name}"));
}

private string GetParameterTypeNames(FunctionSignature function)
{
    string parameterTypes = function.GetParameterTypeNames();

    if (parameterTypes.Length > 0)
        parameterTypes = ", " + parameterTypes;

    return parameterTypes;
}

private FieldInfo GetPromotedStruct(string fieldName)
{
    foreach (FieldInfo field in StructFields)
    {
        if (field.Name.Equals(fieldName, StringComparison.Ordinal))
            return field;
    }

    return null;
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
