//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 08:48:37 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using ptwo = go.p2_package;
using go;

#pragma warning disable CS0660, CS0661

namespace go {
namespace cmd {
namespace api {
namespace testdata {
namespace src {
namespace pkg
{
    public static partial class p1_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface Private
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static Private As<T>(in T target) => (Private<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static Private As<T>(ptr<T> target_ptr) => (Private<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static Private? As(object target) =>
                typeof(Private<>).CreateInterfaceHandler<Private>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class Private<T> : Private
        {
            private T m_target;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.Value;

                    return ref m_target;
                }
            }

            public Private(in T target) => m_target = target;

            public Private(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void XByRef(ref T value);
            private delegate void XByVal(T value);

            private static readonly XByRef s_XByRef;
            private static readonly XByVal s_XByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void X()
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.Value;
                if (s_XByRef is null)
                {
                    s_XByVal!(target);
                    return;
                }

                s_XByRef(ref target);
                return;
                
            }

            private delegate void yByRef(ref T value);
            private delegate void yByVal(T value);

            private static readonly yByRef s_yByRef;
            private static readonly yByVal s_yByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void y()
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.Value;
                if (s_yByRef is null)
                {
                    s_yByVal!(target);
                    return;
                }

                s_yByRef(ref target);
                return;
                
            }
            
            public string ToString(string format, IFormatProvider formatProvider) => format;

            [DebuggerStepperBoundary]
            static Private()
            {
                Type targetType = typeof(T);
                Type targetTypeByRef = targetType.MakeByRefType();
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByRef.GetExtensionMethod("X");

                if (!(extensionMethod is null))
                    s_XByRef = extensionMethod.CreateStaticDelegate(typeof(XByRef)) as XByRef;

                if (s_XByRef is null)
                {
                    extensionMethod = targetType.GetExtensionMethod("X");

                    if (!(extensionMethod is null))
                        s_XByVal = extensionMethod.CreateStaticDelegate(typeof(XByVal)) as XByVal;
                }

                if (s_XByRef is null && s_XByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement Private.X method", new Exception("X"));

               extensionMethod = targetTypeByRef.GetExtensionMethod("y");

                if (!(extensionMethod is null))
                    s_yByRef = extensionMethod.CreateStaticDelegate(typeof(yByRef)) as yByRef;

                if (s_yByRef is null)
                {
                    extensionMethod = targetType.GetExtensionMethod("y");

                    if (!(extensionMethod is null))
                        s_yByVal = extensionMethod.CreateStaticDelegate(typeof(yByVal)) as yByVal;
                }

                if (s_yByRef is null && s_yByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement Private.y method", new Exception("y"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator Private<T>(in ptr<T> target_ptr) => new Private<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator Private<T>(in T target) => new Private<T>(target);

            // Enable comparisons between nil and Private<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(Private<T> value, NilType nil) => Activator.CreateInstance<Private<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(Private<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, Private<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, Private<T> value) => value != nil;
        }
    }
}}}}}}

namespace go
{
    public static class p1_PrivateExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.cmd.api.testdata.src.pkg.p1_package.Private target)
        {
            try
            {
                return ((go.cmd.api.testdata.src.pkg.p1_package.Private<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.cmd.api.testdata.src.pkg.p1_package.Private target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.cmd.api.testdata.src.pkg.p1_package.Private target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.cmd.api.testdata.src.pkg.p1_package.Private<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.cmd.api.testdata.src.pkg.p1_package.Private target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}