//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 08:53:20 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using sort = go.sort_package;
using go;

namespace go {
namespace cmd {
namespace compile {
namespace @internal
{
    public static partial class ssa_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct Cache
        {
            // Constructors
            public Cache(NilType _)
            {
                this.values = default;
                this.blocks = default;
                this.locs = default;
                this.varLocs = default;
                this.curVarLoc = default;
                this.stackAllocState = default;
                this.domblockstore = default;
                this.scrSparse = default;
            }

            public Cache(array<Value> values = default, array<Block> blocks = default, array<Location> locs = default, slice<VarLoc> varLocs = default, long curVarLoc = default, ref ptr<stackAllocState> stackAllocState = default, slice<ID> domblockstore = default, slice<ref sparseSet> scrSparse = default)
            {
                this.values = values;
                this.blocks = blocks;
                this.locs = locs;
                this.varLocs = varLocs;
                this.curVarLoc = curVarLoc;
                this.stackAllocState = stackAllocState;
                this.domblockstore = domblockstore;
                this.scrSparse = scrSparse;
            }

            // Enable comparisons between nil and Cache struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(Cache value, NilType nil) => value.Equals(default(Cache));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(Cache value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, Cache value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, Cache value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator Cache(NilType nil) => default(Cache);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static Cache Cache_cast(dynamic value)
        {
            return new Cache(value.values, value.blocks, value.locs, value.varLocs, value.curVarLoc, ref value.stackAllocState, value.domblockstore, value.scrSparse);
        }
    }
}}}}