//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 08:53:42 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using obj = go.cmd.@internal.obj_package;
using fmt = go.fmt_package;
using strings = go.strings_package;
using go;

namespace go {
namespace cmd {
namespace compile {
namespace @internal
{
    public static partial class ssa_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct VarLoc
        {
            // Constructors
            public VarLoc(NilType _)
            {
                this.Start = default;
                this.End = default;
                this.StartProg = default;
                this.EndProg = default;
                this.StartPC = default;
                this.EndPC = default;
                this.Registers = default;
                this.OnStack = default;
                this.StackLocation = default;
            }

            public VarLoc(ref ptr<Value> Start = default, ref ptr<Value> End = default, ref ptr<obj.Prog> StartProg = default, ref ptr<obj.Prog> EndProg = default, long StartPC = default, long EndPC = default, RegisterSet Registers = default, bool OnStack = default, SlotID StackLocation = default)
            {
                this.Start = Start;
                this.End = End;
                this.StartProg = StartProg;
                this.EndProg = EndProg;
                this.StartPC = StartPC;
                this.EndPC = EndPC;
                this.Registers = Registers;
                this.OnStack = OnStack;
                this.StackLocation = StackLocation;
            }

            // Enable comparisons between nil and VarLoc struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(VarLoc value, NilType nil) => value.Equals(default(VarLoc));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(VarLoc value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, VarLoc value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, VarLoc value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator VarLoc(NilType nil) => default(VarLoc);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static VarLoc VarLoc_cast(dynamic value)
        {
            return new VarLoc(ref value.Start, ref value.End, ref value.StartProg, ref value.EndProg, value.StartPC, value.EndPC, value.Registers, value.OnStack, value.StackLocation);
        }
    }
}}}}