//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 09 04:58:42 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using bytes = go.bytes_package;
using io = go.io_package;
using syntax = go.regexp.syntax_package;
using strconv = go.strconv_package;
using strings = go.strings_package;
using sync = go.sync_package;
using unicode = go.unicode_package;
using utf8 = go.unicode.utf8_package;

#nullable enable

namespace go
{
    public static partial class regexp_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct inputString
        {
            // Constructors
            public inputString(NilType _)
            {
                this.str = default;
            }

            public inputString(@string str = default)
            {
                this.str = str;
            }

            // Enable comparisons between nil and inputString struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(inputString value, NilType nil) => value.Equals(default(inputString));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(inputString value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, inputString value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, inputString value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator inputString(NilType nil) => default(inputString);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        private static inputString inputString_cast(dynamic value)
        {
            return new inputString(value.str);
        }
    }
}