global using complex128 = global::System.Numerics.Complex;
global using float32 = global::System.Single;
global using float64 = global::System.Double;
global using GoTag = global::System.ComponentModel.DescriptionAttribute;
global using GoUntyped = global::System.Numerics.BigInteger;
global using int16 = global::System.Int16;
global using int32 = global::System.Int32;
global using int64 = global::System.Int64;
global using int8 = global::System.SByte;
global using rune = global::System.Int32;
global using uint16 = global::System.UInt16;
global using uint32 = global::System.UInt32;
global using uint64 = global::System.UInt64;
global using uint8 = global::System.Byte;
global using uintptr = global::System.UIntPtr;
global using static global::go.builtin;