//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2022 March 13 06:35:53 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using bytes = go.bytes_package;
using fmt = go.fmt_package;
using template = go.html.template_package;
using trace = go.@internal.trace_package;
using log = go.log_package;
using math = go.math_package;
using http = go.net.http_package;
using url = go.net.url_package;
using reflect = go.reflect_package;
using sort = go.sort_package;
using strconv = go.strconv_package;
using strings = go.strings_package;
using time = go.time_package;

#nullable enable

namespace go
{
    public static partial class main_package
    {
        [GeneratedCode("go2cs", "0.1.2.0")]
        private partial struct annotationAnalysisResult
        {
            // Constructors
            public annotationAnalysisResult(NilType _)
            {
                this.tasks = default;
                this.regions = default;
                this.gcEvents = default;
            }

            public annotationAnalysisResult(map<ulong, ptr<taskDesc>> tasks = default, map<regionTypeID, slice<regionDesc>> regions = default, slice<ptr<trace.Event>> gcEvents = default)
            {
                this.tasks = tasks;
                this.regions = regions;
                this.gcEvents = gcEvents;
            }

            // Enable comparisons between nil and annotationAnalysisResult struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(annotationAnalysisResult value, NilType nil) => value.Equals(default(annotationAnalysisResult));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(annotationAnalysisResult value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, annotationAnalysisResult value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, annotationAnalysisResult value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator annotationAnalysisResult(NilType nil) => default(annotationAnalysisResult);
        }

        [GeneratedCode("go2cs", "0.1.2.0")]
        private static annotationAnalysisResult annotationAnalysisResult_cast(dynamic value)
        {
            return new annotationAnalysisResult(value.tasks, value.regions, value.gcEvents);
        }
    }
}