//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2022 March 06 23:35:48 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;

using go;

#nullable enable

namespace go {
namespace image
{
    public static partial class color_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct RGBA
        {
            // Constructors
            public RGBA(NilType _)
            {
                this.R = default;
                this.G = default;
                this.B = default;
                this.A = default;
            }

            public RGBA(byte R = default, byte G = default, byte B = default, byte A = default)
            {
                this.R = R;
                this.G = G;
                this.B = B;
                this.A = A;
            }

            // Enable comparisons between nil and RGBA struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(RGBA value, NilType nil) => value.Equals(default(RGBA));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(RGBA value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, RGBA value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, RGBA value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator RGBA(NilType nil) => default(RGBA);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static RGBA RGBA_cast(dynamic value)
        {
            return new RGBA(value.R, value.G, value.B, value.A);
        }
    }
}}