//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 08 04:58:57 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using context = go.context_package;
using driver = go.database.sql.driver_package;
using errors = go.errors_package;
using fmt = go.fmt_package;
using io = go.io_package;
using reflect = go.reflect_package;
using runtime = go.runtime_package;
using sort = go.sort_package;
using strconv = go.strconv_package;
using sync = go.sync_package;
using atomic = go.sync.atomic_package;
using time = go.time_package;
using go;

namespace go {
namespace database
{
    public static partial class sql_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct NullInt32
        {
            // Constructors
            public NullInt32(NilType _)
            {
                this.Int32 = default;
                this.Valid = default;
            }

            public NullInt32(int Int32 = default, bool Valid = default)
            {
                this.Int32 = Int32;
                this.Valid = Valid;
            }

            // Enable comparisons between nil and NullInt32 struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NullInt32 value, NilType nil) => value.Equals(default(NullInt32));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NullInt32 value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, NullInt32 value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, NullInt32 value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator NullInt32(NilType nil) => default(NullInt32);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static NullInt32 NullInt32_cast(dynamic value)
        {
            return new NullInt32(value.Int32, value.Valid);
        }
    }
}}