//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2022 March 06 22:13:10 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using syscall = go.syscall_package;
using @unsafe = go.@unsafe_package;
using go;

#nullable enable

namespace go {
namespace @internal {
namespace syscall
{
    public static partial class windows_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct LocalGroupUserInfo0
        {
            // Constructors
            public LocalGroupUserInfo0(NilType _)
            {
                this.Name = default;
            }

            public LocalGroupUserInfo0(ref ptr<ushort> Name = default)
            {
                this.Name = Name;
            }

            // Enable comparisons between nil and LocalGroupUserInfo0 struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(LocalGroupUserInfo0 value, NilType nil) => value.Equals(default(LocalGroupUserInfo0));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(LocalGroupUserInfo0 value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, LocalGroupUserInfo0 value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, LocalGroupUserInfo0 value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator LocalGroupUserInfo0(NilType nil) => default(LocalGroupUserInfo0);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static LocalGroupUserInfo0 LocalGroupUserInfo0_cast(dynamic value)
        {
            return new LocalGroupUserInfo0(ref value.Name);
        }
    }
}}}