// Code generated by mkconsts.go. DO NOT EDIT.
//go:build goexperiment.regabiargs
namespace go.@internal;

partial class goexperiment_package {

public const bool RegabiArgs = true;

public static readonly UntypedInt RegabiArgsInt = 1;

} // end goexperiment_package
