//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2018 August 09 01:21:20 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using static go.builtin;
using fmt = go.fmt_package;

namespace go
{
    public static partial class main_package
    {
        [GeneratedCode("go2cs", "0.1.1.0")]
        public partial struct ColorList : EmptyInterface
        {
            // Constructors
            public ColorList(NilType _)
            {
                this.Total = default;
                this.Color = default;
                this.Next = default;
                this.NextNext = default;
            }

            public ColorList(@int Total, @string Color, ref Ptr<ColorList> Next, ref Ptr<Ptr<ColorList>> NextNext)
            {
                this.Total = Total;
                this.Color = Color;
                this.Next = Next;
                this.NextNext = NextNext;
            }

            // Enable comparisons between nil and ColorList struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(ColorList value, NilType nil) => value.Equals(default(ColorList));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(ColorList value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, ColorList value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, ColorList value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator ColorList(NilType nil) => default(ColorList);
        }

        [GeneratedCode("go2cs", "0.1.1.0")]
        public static ColorList ColorList_cast(dynamic value)
        {
            return new ColorList(value.Total, value.Color, ref value.Next, ref value.NextNext);
        }
    }
}