//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 08 04:57:34 UTC
// </auto-generated>
//---------------------------------------------------------
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using go;

namespace go {
namespace golang.org {
namespace x {
namespace tools {
namespace go {
namespace ssa {
namespace interp {
namespace testdata {
namespace src
{
    public static partial class time_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct Duration
        {
            // Value of the Duration struct
            private readonly long m_value;

            public Duration(long value) => m_value = value;

            // Enable implicit conversions between long and Duration struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator Duration(long value) => new Duration(value);
            
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator long(Duration value) => value.m_value;
            
            // Enable comparisons between nil and Duration struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(Duration value, NilType nil) => value.Equals(default(Duration));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(Duration value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, Duration value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, Duration value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator Duration(NilType nil) => default(Duration);
        }
    }
}}}}}}}}}
