//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 08:37:23 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using sync = go.sync_package;
using atomic = go.sync.atomic_package;

#pragma warning disable CS0660, CS0661

namespace go
{
    public static partial class syscall_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial interface RoutingMessage
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static RoutingMessage As<T>(in T target) => (RoutingMessage<T>)target!;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static RoutingMessage As<T>(ptr<T> target_ptr) => (RoutingMessage<T>)target_ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static RoutingMessage? As(object target) =>
                typeof(RoutingMessage<>).CreateInterfaceHandler<RoutingMessage>(target);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public class RoutingMessage<T> : RoutingMessage
        {
            private T m_target;
            private readonly ptr<T>? m_target_ptr;
            private readonly bool m_target_is_ptr;

            public ref T Target
            {
                get
                {
                    if (m_target_is_ptr && !(m_target_ptr is null))
                        return ref m_target_ptr.Value;

                    return ref m_target;
                }
            }

            public RoutingMessage(in T target) => m_target = target;

            public RoutingMessage(ptr<T> target_ptr)
            {
                m_target_ptr = target_ptr;
                m_target_is_ptr = true;
            }

            private delegate void unimplementedByRef(ref T value);
            private delegate void unimplementedByVal(T value);

            private static readonly unimplementedByRef s_unimplementedByRef;
            private static readonly unimplementedByVal s_unimplementedByVal;

            [DebuggerNonUserCode, MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void unimplemented()
            {
                T target = m_target;

                if (m_target_is_ptr && !(m_target_ptr is null))
                    target = m_target_ptr.Value;
                if (s_unimplementedByRef is null)
                {
                    s_unimplementedByVal!(target);
                    return;
                }

                s_unimplementedByRef(ref target);
                return;
                
            }
            
            public string ToString(string format, IFormatProvider formatProvider) => format;

            [DebuggerStepperBoundary]
            static RoutingMessage()
            {
                Type targetType = typeof(T);
                Type targetTypeByRef = targetType.MakeByRefType();
                MethodInfo extensionMethod;

               extensionMethod = targetTypeByRef.GetExtensionMethod("unimplemented");

                if (!(extensionMethod is null))
                    s_unimplementedByRef = extensionMethod.CreateStaticDelegate(typeof(unimplementedByRef)) as unimplementedByRef;

                if (s_unimplementedByRef is null)
                {
                    extensionMethod = targetType.GetExtensionMethod("unimplemented");

                    if (!(extensionMethod is null))
                        s_unimplementedByVal = extensionMethod.CreateStaticDelegate(typeof(unimplementedByVal)) as unimplementedByVal;
                }

                if (s_unimplementedByRef is null && s_unimplementedByVal is null)
                    throw new NotImplementedException($"{targetType.FullName} does not implement RoutingMessage.unimplemented method", new Exception("unimplemented"));
            }

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator RoutingMessage<T>(in ptr<T> target_ptr) => new RoutingMessage<T>(target_ptr);

            [MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
            public static explicit operator RoutingMessage<T>(in T target) => new RoutingMessage<T>(target);

            // Enable comparisons between nil and RoutingMessage<T> interface instance
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(RoutingMessage<T> value, NilType nil) => Activator.CreateInstance<RoutingMessage<T>>().Equals(value);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(RoutingMessage<T> value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, RoutingMessage<T> value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, RoutingMessage<T> value) => value != nil;
        }
    }
}

namespace go
{
    public static class syscall_RoutingMessageExtensions
    {
        private static readonly ConcurrentDictionary<Type, MethodInfo> s_conversionOperators = new ConcurrentDictionary<Type, MethodInfo>();

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static T _<T>(this go.syscall_package.RoutingMessage target)
        {
            try
            {
                return ((go.syscall_package.RoutingMessage<T>)target).Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(typeof(T))}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _<T>(this go.syscall_package.RoutingMessage target, out T result)
        {
            try
            {
                result = target._<T>();
                return true;
            }
            catch (PanicException)
            {
                result = default!;
                return false;
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static object? _(this go.syscall_package.RoutingMessage target, Type type)
        {
            try
            {
                MethodInfo? conversionOperator = s_conversionOperators.GetOrAdd(type, _ => typeof(go.syscall_package.RoutingMessage<>).GetExplicitGenericConversionOperator(type));

                if (conversionOperator is null)
                    throw new PanicException($"interface conversion: failed to create converter for {GetGoTypeName(target.GetType())} to {GetGoTypeName(type)}");

                dynamic? result = conversionOperator.Invoke(null, new object[] { target });
                return result?.Target;
            }
            catch (NotImplementedException ex)
            {
                throw new PanicException($"interface conversion: {GetGoTypeName(target.GetType())} is not {GetGoTypeName(type)}: missing method {ex.InnerException?.Message}");
            }
        }

        [GeneratedCode("go2cs", "0.1.0.0"), MethodImpl(MethodImplOptions.AggressiveInlining), DebuggerNonUserCode]
        public static bool _(this go.syscall_package.RoutingMessage target, Type type, out object? result)
        {
            try
            {
                result = target._(type);
                return true;
            }
            catch (PanicException)
            {
                result = type.IsValueType ? Activator.CreateInstance(type) : null;
                return false;
            }
        }
    }
}