//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 09 05:45:30 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using bytes = go.bytes_package;
using sha256 = go.crypto.sha256_package;
using hex = go.encoding.hex_package;
using errors = go.errors_package;
using fmt = go.fmt_package;
using io = go.io_package;
using ioutil = go.io.ioutil_package;
using os = go.os_package;
using filepath = go.path.filepath_package;
using strconv = go.strconv_package;
using strings = go.strings_package;
using time = go.time_package;
using renameio = go.cmd.go.@internal.renameio_package;
using go;

#nullable enable

namespace go {
namespace cmd {
namespace go {
namespace @internal
{
    public static partial class cache_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        public partial struct Cache
        {
            // Constructors
            public Cache(NilType _)
            {
                this.dir = default;
                this.now = default;
            }

            public Cache(@string dir = default, Func<time.Time> now = default)
            {
                this.dir = dir;
                this.now = now;
            }

            // Enable comparisons between nil and Cache struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(Cache value, NilType nil) => value.Equals(default(Cache));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(Cache value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, Cache value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, Cache value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator Cache(NilType nil) => default(Cache);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static Cache Cache_cast(dynamic value)
        {
            return new Cache(value.dir, value.now);
        }
    }
}}}}