//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2022 November 20 18:37:03 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections;
using System.Runtime.CompilerServices;

#nullable enable

namespace go
{
    public static partial class main_package
    {
        [GeneratedCode("go2cs", "0.1.2.0")]
        public partial struct PeopleByAge : ISlice
        {
            // Value of the PeopleByAge struct
            private readonly slice<Person> m_value;
            
            public Person[] Source => m_value;
            
            public ISlice<Person> Append(Person[] elems) => m_value.Append(elems);
            
            public nint Low => ((ISlice)m_value).Low;

            public nint High => ((ISlice)m_value).High;

            public nint Capacity => ((ISlice)m_value).Capacity;

            public nint Available => ((ISlice)m_value).Available;

            public nint Length => ((IArray)m_value).Length;

            Array IArray.Source => ((IArray)m_value).Source!;

            object? IArray.this[nint index]
            {
                get => ((IArray)m_value)[index];
                set => ((IArray)m_value)[index] = value;
            }
            
            public ref Person this[nint index]
            {
                get => ref m_value[index];
            }
            
            public ISlice? Append(object[] elems) => ((ISlice)m_value).Append(elems);

            public IEnumerator GetEnumerator() => ((IEnumerable)m_value).GetEnumerator();

            public object Clone() => ((ICloneable)m_value).Clone();

            public PeopleByAge(slice<Person> value) => m_value = value;

            // Enable implicit conversions between slice<Person> and PeopleByAge struct
            public static implicit operator PeopleByAge(slice<Person> value) => new PeopleByAge(value);
            
            public static implicit operator slice<Person>(PeopleByAge value) => value.m_value;
            
            // Enable comparisons between nil and PeopleByAge struct
            public static bool operator ==(PeopleByAge value, NilType nil) => value.Equals(default(PeopleByAge));

            public static bool operator !=(PeopleByAge value, NilType nil) => !(value == nil);

            public static bool operator ==(NilType nil, PeopleByAge value) => value == nil;

            public static bool operator !=(NilType nil, PeopleByAge value) => value != nil;

            public static implicit operator PeopleByAge(NilType nil) => default(PeopleByAge);
        }
    }
}
