#theme: jekyll-theme-cayman
remote_theme: chris1111/cayman-dark
title: go2cs
description: Golang to C# Converter
github:
  repository_name: ritchiecarroll/go2cs
  owner_url: https://github.com/ritchiecarroll
  owner_name: J. Ritchie Carroll
plugins:
  - jemoji
