theme: jekyll-theme-cayman
title: go2cs
description: Golang to C# Converter
github:
  repository_name: GridProtectionAlliance/go2cs
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
