//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 October 08 04:59:33 UTC
// </auto-generated>
//---------------------------------------------------------
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using go;

namespace go {
namespace image
{
    public static partial class jpeg_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct quantIndex
        {
            // Value of the quantIndex struct
            private readonly long m_value;

            public quantIndex(long value) => m_value = value;

            // Enable implicit conversions between long and quantIndex struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator quantIndex(long value) => new quantIndex(value);
            
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator long(quantIndex value) => value.m_value;
            
            // Enable comparisons between nil and quantIndex struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(quantIndex value, NilType nil) => value.Equals(default(quantIndex));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(quantIndex value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, quantIndex value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, quantIndex value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator quantIndex(NilType nil) => default(quantIndex);
        }
    }
}}
