//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 10:10:44 UTC
// </auto-generated>
//---------------------------------------------------------
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using go;

namespace go {
namespace compress
{
    public static partial class bzip2_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct huffmanCodes
        {
            // Value of the huffmanCodes struct
            private readonly slice<huffmanCode> m_value;

            public huffmanCodes(slice<huffmanCode> value) => m_value = value;

            // Enable implicit conversions between slice<huffmanCode> and huffmanCodes struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator huffmanCodes(slice<huffmanCode> value) => new huffmanCodes(value);
            
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator slice<huffmanCode>(huffmanCodes value) => value.m_value;
            
            // Enable comparisons between nil and huffmanCodes struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(huffmanCodes value, NilType nil) => value.Equals(default(huffmanCodes));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(huffmanCodes value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, huffmanCodes value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, huffmanCodes value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator huffmanCodes(NilType nil) => default(huffmanCodes);
        }
    }
}}
