//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 09:26:03 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using src = go.cmd.@internal.src_package;
using go;

namespace go {
namespace cmd {
namespace compile {
namespace @internal
{
    public static partial class syntax_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        [PromotedStruct(typeof(decl))]
        public partial struct FuncDecl
        {
            // decl structure promotion - sourced from value copy
            private readonly ptr<decl> m_declRef;

            private ref decl decl_val => ref m_declRef.Value;

            // Constructors
            public FuncDecl(NilType _)
            {
                this.Attr = default;
                this.Recv = default;
                this.Name = default;
                this.Type = default;
                this.Body = default;
                this.Pragma = default;
                this.m_declRef = new ptr<decl>(new decl(nil));
            }

            public FuncDecl(map<@string, bool> Attr = default, ref ptr<Field> Recv = default, ref ptr<Name> Name = default, ref ptr<FuncType> Type = default, ref ptr<BlockStmt> Body = default, Pragma Pragma = default, decl decl = default)
            {
                this.Attr = Attr;
                this.Recv = Recv;
                this.Name = Name;
                this.Type = Type;
                this.Body = Body;
                this.Pragma = Pragma;
                this.m_declRef = new ptr<decl>(decl);
            }

            // Enable comparisons between nil and FuncDecl struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(FuncDecl value, NilType nil) => value.Equals(default(FuncDecl));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(FuncDecl value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, FuncDecl value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, FuncDecl value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator FuncDecl(NilType nil) => default(FuncDecl);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        public static FuncDecl FuncDecl_cast(dynamic value)
        {
            return new FuncDecl(value.Attr, ref value.Recv, ref value.Name, ref value.Type, ref value.Body, value.Pragma, value.decl);
        }
    }
}}}}