//---------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this
//     file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generated on 2020 August 29 09:26:26 UTC
// </auto-generated>
//---------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using static go.builtin;
using fmt = go.fmt_package;
using io = go.io_package;
using unicode = go.unicode_package;
using utf8 = go.unicode.utf8_package;
using go;

namespace go {
namespace cmd {
namespace compile {
namespace @internal
{
    public static partial class syntax_package
    {
        [GeneratedCode("go2cs", "0.1.0.0")]
        private partial struct scanner
        {
            // Constructors
            public scanner(NilType _)
            {
                this.source = default;
                this.pragh = default;
                this.nlsemi = default;
                this.line = default;
                this.col = default;
                this.tok = default;
                this.lit = default;
                this.kind = default;
                this.op = default;
                this.prec = default;
            }

            public scanner(source source = default, Action<ulong, ulong, @string> pragh = default, bool nlsemi = default, ulong line = default, ulong col = default, token tok = default, @string lit = default, LitKind kind = default, Operator op = default, long prec = default)
            {
                this.source = source;
                this.pragh = pragh;
                this.nlsemi = nlsemi;
                this.line = line;
                this.col = col;
                this.tok = tok;
                this.lit = lit;
                this.kind = kind;
                this.op = op;
                this.prec = prec;
            }

            // Enable comparisons between nil and scanner struct
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(scanner value, NilType nil) => value.Equals(default(scanner));

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(scanner value, NilType nil) => !(value == nil);

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator ==(NilType nil, scanner value) => value == nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static bool operator !=(NilType nil, scanner value) => value != nil;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public static implicit operator scanner(NilType nil) => default(scanner);
        }

        [GeneratedCode("go2cs", "0.1.0.0")]
        private static scanner scanner_cast(dynamic value)
        {
            return new scanner(value.source, value.pragh, value.nlsemi, value.line, value.col, value.tok, value.lit, value.kind, value.op, value.prec);
        }
    }
}}}}