// Copyright 2016 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
namespace go.encoding;

using utf8 = unicode.utf8_package;
using unicode;

partial class json_package {

// safeSet holds the value true if the ASCII character with the given array
// position can be represented inside a JSON string without any further
// escaping.
//
// All values are true except for the ASCII control characters (0-31), the
// double quote ("), and the backslash character ("\").
internal static array<bool> safeSet = new array<bool>(128){
    [(rune)' '] = true,
    [(rune)'!'] = true,
    [(rune)'"'] = false,
    [(rune)'#'] = true,
    [(rune)'$'] = true,
    [(rune)'%'] = true,
    [(rune)'&'] = true,
    [(rune)'\'] = true,
    [(rune)'('] = true,
    [(rune)')'] = true,
    [(rune)'*'] = true,
    [(rune)'+'] = true,
    [(rune)','] = true,
    [(rune)'-'] = true,
    [(rune)'.'] = true,
    [(rune)'/'] = true,
    [(rune)'0'] = true,
    [(rune)'1'] = true,
    [(rune)'2'] = true,
    [(rune)'3'] = true,
    [(rune)'4'] = true,
    [(rune)'5'] = true,
    [(rune)'6'] = true,
    [(rune)'7'] = true,
    [(rune)'8'] = true,
    [(rune)'9'] = true,
    [(rune)':'] = true,
    [(rune)';'] = true,
    [(rune)'<'] = true,
    [(rune)'='] = true,
    [(rune)'>'] = true,
    [(rune)'?'] = true,
    [(rune)'@'] = true,
    [(rune)'A'] = true,
    [(rune)'B'] = true,
    [(rune)'C'] = true,
    [(rune)'D'] = true,
    [(rune)'E'] = true,
    [(rune)'F'] = true,
    [(rune)'G'] = true,
    [(rune)'H'] = true,
    [(rune)'I'] = true,
    [(rune)'J'] = true,
    [(rune)'K'] = true,
    [(rune)'L'] = true,
    [(rune)'M'] = true,
    [(rune)'N'] = true,
    [(rune)'O'] = true,
    [(rune)'P'] = true,
    [(rune)'Q'] = true,
    [(rune)'R'] = true,
    [(rune)'S'] = true,
    [(rune)'T'] = true,
    [(rune)'U'] = true,
    [(rune)'V'] = true,
    [(rune)'W'] = true,
    [(rune)'X'] = true,
    [(rune)'Y'] = true,
    [(rune)'Z'] = true,
    [(rune)'['] = true,
    [(rune)'\'] = false,
    [(rune)']'] = true,
    [(rune)'^'] = true,
    [(rune)'_'] = true,
    [(rune)'`'] = true,
    [(rune)'a'] = true,
    [(rune)'b'] = true,
    [(rune)'c'] = true,
    [(rune)'d'] = true,
    [(rune)'e'] = true,
    [(rune)'f'] = true,
    [(rune)'g'] = true,
    [(rune)'h'] = true,
    [(rune)'i'] = true,
    [(rune)'j'] = true,
    [(rune)'k'] = true,
    [(rune)'l'] = true,
    [(rune)'m'] = true,
    [(rune)'n'] = true,
    [(rune)'o'] = true,
    [(rune)'p'] = true,
    [(rune)'q'] = true,
    [(rune)'r'] = true,
    [(rune)'s'] = true,
    [(rune)'t'] = true,
    [(rune)'u'] = true,
    [(rune)'v'] = true,
    [(rune)'w'] = true,
    [(rune)'x'] = true,
    [(rune)'y'] = true,
    [(rune)'z'] = true,
    [(rune)'{'] = true,
    [(rune)'|'] = true,
    [(rune)'}'] = true,
    [(rune)'~'] = true,
    [(rune)'\'] = true
};

// htmlSafeSet holds the value true if the ASCII character with the given
// array position can be safely represented inside a JSON string, embedded
// inside of HTML <script> tags, without any additional escaping.
//
// All values are true except for the ASCII control characters (0-31), the
// double quote ("), the backslash character ("\"), HTML opening and closing
// tags ("<" and ">"), and the ampersand ("&").
internal static array<bool> htmlSafeSet = new array<bool>(128){
    [(rune)' '] = true,
    [(rune)'!'] = true,
    [(rune)'"'] = false,
    [(rune)'#'] = true,
    [(rune)'$'] = true,
    [(rune)'%'] = true,
    [(rune)'&'] = false,
    [(rune)'\'] = true,
    [(rune)'('] = true,
    [(rune)')'] = true,
    [(rune)'*'] = true,
    [(rune)'+'] = true,
    [(rune)','] = true,
    [(rune)'-'] = true,
    [(rune)'.'] = true,
    [(rune)'/'] = true,
    [(rune)'0'] = true,
    [(rune)'1'] = true,
    [(rune)'2'] = true,
    [(rune)'3'] = true,
    [(rune)'4'] = true,
    [(rune)'5'] = true,
    [(rune)'6'] = true,
    [(rune)'7'] = true,
    [(rune)'8'] = true,
    [(rune)'9'] = true,
    [(rune)':'] = true,
    [(rune)';'] = true,
    [(rune)'<'] = false,
    [(rune)'='] = true,
    [(rune)'>'] = false,
    [(rune)'?'] = true,
    [(rune)'@'] = true,
    [(rune)'A'] = true,
    [(rune)'B'] = true,
    [(rune)'C'] = true,
    [(rune)'D'] = true,
    [(rune)'E'] = true,
    [(rune)'F'] = true,
    [(rune)'G'] = true,
    [(rune)'H'] = true,
    [(rune)'I'] = true,
    [(rune)'J'] = true,
    [(rune)'K'] = true,
    [(rune)'L'] = true,
    [(rune)'M'] = true,
    [(rune)'N'] = true,
    [(rune)'O'] = true,
    [(rune)'P'] = true,
    [(rune)'Q'] = true,
    [(rune)'R'] = true,
    [(rune)'S'] = true,
    [(rune)'T'] = true,
    [(rune)'U'] = true,
    [(rune)'V'] = true,
    [(rune)'W'] = true,
    [(rune)'X'] = true,
    [(rune)'Y'] = true,
    [(rune)'Z'] = true,
    [(rune)'['] = true,
    [(rune)'\'] = false,
    [(rune)']'] = true,
    [(rune)'^'] = true,
    [(rune)'_'] = true,
    [(rune)'`'] = true,
    [(rune)'a'] = true,
    [(rune)'b'] = true,
    [(rune)'c'] = true,
    [(rune)'d'] = true,
    [(rune)'e'] = true,
    [(rune)'f'] = true,
    [(rune)'g'] = true,
    [(rune)'h'] = true,
    [(rune)'i'] = true,
    [(rune)'j'] = true,
    [(rune)'k'] = true,
    [(rune)'l'] = true,
    [(rune)'m'] = true,
    [(rune)'n'] = true,
    [(rune)'o'] = true,
    [(rune)'p'] = true,
    [(rune)'q'] = true,
    [(rune)'r'] = true,
    [(rune)'s'] = true,
    [(rune)'t'] = true,
    [(rune)'u'] = true,
    [(rune)'v'] = true,
    [(rune)'w'] = true,
    [(rune)'x'] = true,
    [(rune)'y'] = true,
    [(rune)'z'] = true,
    [(rune)'{'] = true,
    [(rune)'|'] = true,
    [(rune)'}'] = true,
    [(rune)'~'] = true,
    [(rune)'\'] = true
};

} // end json_package
